name: Maven CICD 
on:
  push:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        id: mavn-build
        run: |
          cd my-app
          mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MAVENBUILD_PERSONALTOKEN }}

